name: Main
on:
  push:
    branches:
      - main
jobs:
  website_docker_build_push:
    name: Build & push website Docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Set REPO (lowercase)
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          outputs: type=image,oci-mediatypes=false
          push: true
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.SHORT_SHA }}
